#/etc/NetworkManager/dnsmasq.d/01-DNS-dnsmasq-routednet.conf
# local dns -- CHANGE: replace lab.example.com with your own domain
local=/routednet.lab.example.com/
addn-hosts=/etc/virsh-routednet-dnsmasq.hosts
address=/apps-crc.testing/127.0.0.1

# Adding SNO wildcard entries. This requires the use of
# address rather than addn-hosts, as the latter does not support wildcards.
##### SNO
address=/.acm.routednet.labs.lab.example.com/192.168.192.10
##### MCE
address=/.apps.mce.routednet.labs.lab.example.com/192.168.192.101
##### HCP
address=/.apps.hcp-1.routednet.labs.lab.example.com/192.168.192.14
address=/.apps.hcp-2.routednet.labs.lab.example.com/192.168.192.17

domain-needed
bogus-priv

# Automatically add <domain> to simple names in a hosts-file.
expand-hosts

# Upstream public
no-poll
server=8.8.8.8
